name: testing-workflow
on: [push, pull_request]
jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -dev
    -name: Run pylint
      run: |
        pipenv run pylint app
    -name: Run tests
      run: |
        pipenv run nosetests